import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TopMenu } from "@/components/ui/topMenu/TopMenu";
import { Footer } from "@/components/ui/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Development Real Time Stratery",
  description: "Generated by create next app",
  openGraph: {
    title: 'Development Real Time Stratery',
    description: 'We build and support real time',
    url: 'https://www.drts.us',
    siteName: 'Development Real Time Stratery',
    images: [
      {
        url: '/drts_v2.png', // Ruta relativa desde `public`
        width: 1200, // Ancho recomendado
        height: 630, // Alto recomendado
        alt: 'drts_logo',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/drts_v2.ico" type="image/x-icon" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <TopMenu/> */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
